name: 'WinGet Updater'
description: 'Publish updates of your application to Windows Package Manager automatically.'

branding:
  color: blue
  icon: upload-cloud

inputs:
  komac-version:
    description: 'Which Komac version to use.'
    required: false
    default: '2.3.0'
  komac-token:
    description: 'The GitHub token to use for authentication.'
    required: true
  identifier:
    description: 'The PackageIdentifier of the package (case-sensitive).'
    required: true
  repo:
    description: 'The GitHub repository to check for the latest release.'
    required: true
  url:
    description: 'The URL(s) to the latest release.'
    required: true
  custom-fork-owner:
    description: 'Custom winget-pkgs fork owner'
    required: false
  submit:
    description: 'Decide if Pull Request should be submitted'
    required: false
    default: 'true'
  pre-release:
    description: 'Decide if pre-releases should be considered'
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: Check if Package Exists in winget-pkgs Repository
      uses: actions/github-script@v7
      with:
        script: |
          const pkgid = "${{ inputs.identifier }}";
          const url = `https://github.com/microsoft/winget-pkgs/tree/master/manifests/${pkgid.charAt(0).toLowerCase()}/${pkgid.replaceAll('.', '/')}`;
          const headers = { method: 'HEAD' };

          const res = await fetch(url, headers);

          if (!res.ok) {
            core.setFailed(`Package ${pkgid} does not exist in the winget-pkgs repository. Please add at least one version of the package before using this action.`);
            process.exit(1);
          }

    - name: Detect Latest Release
      id: latest_release
      uses: actions/github-script@v7
      with:
        script: |
          const [owner, repo] = '${{ inputs.repo }}'.split('/');
          try {
            if('${{ inputs.pre-release }}' == 'true') {
              console.log('Fetching pre-release');
              const res = await fetch(`https://api.github.com/repos/${owner}/${repo}/releases`);
              const releases = await res.json();
              const preRelease = releases.filter(release => release.prerelease)[0];
              const tagNameRaw = preRelease ? preRelease.tag_name : null;
              const tagName = tagNameRaw.startsWith('v') ? tagNameRaw.substring(1) : tagNameRaw;
              return tagName;
            } else {
              console.log('Fetching release');
              let { data } = await github.rest.repos.getLatestRelease({ owner, repo });
              const tagName = data.tag_name.startsWith('v') ? data.tag_name.substring(1) : data.tag_name;
              return tagName;
            } 
          } catch (error) {
            core.setFailed(`Failed to get latest release for repo: ${owner}/${repo}`);
            console.error(error);
            process.exit(1);
          }

    - name: Compose URL
      shell: bash
      run: |
        VERSION=${{ steps.latest_release.outputs.result }}
        URL="${{ inputs.url }}"
        FINAL_URL=$(echo $URL | sed "s/{VERSION}/$VERSION/g")
        echo "FINAL_URL=$FINAL_URL" >> $GITHUB_ENV
        echo "Detected latest Version: ${{ steps.latest_release.outputs.result }}"
        echo "Final URL: $FINAL_URL"

    - name: Run Komac
      uses: michidk/run-komac@v2
      continue-on-error: true
      with:
        komac-version: ${{ inputs.komac-version }}
        custom-fork-owner: ${{ inputs.custom-fork-owner }}
        custom-tool: WinGet Updater
        custom-tool-url: "https://github.com/michidk/winget-updater"
        args: update ${{ inputs.identifier }} --version ${{ steps.latest_release.outputs.result }} --urls $FINAL_URL ${{ inputs.submit == 'true' && '--submit' || '' }} --token ${{ inputs.komac-token }}
